[2025-04-15T01:08:04.219+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-15T01:08:04.310+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: pipeline_garrafa_stanley.ai_feedback manual__2025-04-15T01:07:35.944088+00:00 [queued]>
[2025-04-15T01:08:04.333+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: pipeline_garrafa_stanley.ai_feedback manual__2025-04-15T01:07:35.944088+00:00 [queued]>
[2025-04-15T01:08:04.335+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-04-15T01:08:04.370+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ai_feedback> on 2025-04-15 01:07:35.944088+00:00
[2025-04-15T01:08:04.388+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4511) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-15T01:08:04.392+0000] {standard_task_runner.py:72} INFO - Started process 4513 to run task
[2025-04-15T01:08:04.395+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'pipeline_garrafa_stanley', 'ai_feedback', 'manual__2025-04-15T01:07:35.944088+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmps2d4gqxb']
[2025-04-15T01:08:04.401+0000] {standard_task_runner.py:105} INFO - Job 171: Subtask ai_feedback
[2025-04-15T01:08:04.613+0000] {task_command.py:467} INFO - Running <TaskInstance: pipeline_garrafa_stanley.ai_feedback manual__2025-04-15T01:07:35.944088+00:00 [running]> on host a68e7f38875d
[2025-04-15T01:08:04.888+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='pipeline_garrafa_stanley' AIRFLOW_CTX_TASK_ID='ai_feedback' AIRFLOW_CTX_EXECUTION_DATE='2025-04-15T01:07:35.944088+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-15T01:07:35.944088+00:00'
[2025-04-15T01:08:04.891+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-15T01:08:04.953+0000] {logging_mixin.py:190} INFO - "[{'preco': 319.9981778741879, 'data': '15/04/2025', 'capacidade': '710ml'}, {'preco': 272.5447833433377, 'data': '12/04/2025', 'capacidade': '710ml'}, {'preco': 332.5330719410694, 'data': '11/04/2025', 'capacidade': '1100ml'}, {'preco': 269.0608313067965, 'data': '11/04/2025', 'capacidade': '710ml'}, {'preco': 364.98922935779837, 'data': '14/04/2025', 'capacidade': '1100ml'}, {'preco': 316.3198969072181, 'data': '14/04/2025', 'capacidade': '710ml'}, {'preco': 337.8895705952379, 'data': '12/04/2025', 'capacidade': '1100ml'}, {'preco': 365.1362004662, 'data': '15/04/2025', 'capacidade': '1100ml'}]"
[2025-04-15T01:08:04.956+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ai_feedback.py", line 46, in ai_request
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={os.getenv("GEMINI_KEY")}"
                                                                                                          ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-15T01:08:04.997+0000] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=pipeline_garrafa_stanley, task_id=ai_feedback, run_id=manual__2025-04-15T01:07:35.944088+00:00, execution_date=20250415T010735, start_date=20250415T010804, end_date=20250415T010804
[2025-04-15T01:08:05.124+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-15T01:08:05.127+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 171 for task ai_feedback (name 'os' is not defined; 4513)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ai_feedback.py", line 46, in ai_request
    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key={os.getenv("GEMINI_KEY")}"
                                                                                                          ^^
NameError: name 'os' is not defined. Did you forget to import 'os'
[2025-04-15T01:08:05.179+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-15T01:08:05.261+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-15T01:08:05.272+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
