[2025-04-14T00:05:20.154+0000] {processor.py:186} INFO - Started process (PID=35) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:05:20.166+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:05:20.180+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:05:20.179+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:05:20.247+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:05:20.231+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:05:20.261+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:05:20.494+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.367 seconds
[2025-04-14T00:05:50.567+0000] {processor.py:186} INFO - Started process (PID=45) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:05:50.569+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:05:50.572+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:05:50.572+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:05:50.585+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:05:50.581+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:05:50.588+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:05:50.635+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.075 seconds
[2025-04-14T00:06:21.229+0000] {processor.py:186} INFO - Started process (PID=65) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:06:21.230+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:06:21.233+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:06:21.233+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:06:21.245+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:06:21.241+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:06:21.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:06:21.288+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.071 seconds
[2025-04-14T00:06:51.502+0000] {processor.py:186} INFO - Started process (PID=77) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:06:51.505+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:06:51.508+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:06:51.508+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:06:51.531+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:06:51.524+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:06:51.536+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:06:51.591+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.103 seconds
[2025-04-14T00:07:21.843+0000] {processor.py:186} INFO - Started process (PID=88) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:07:21.845+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:07:21.848+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:07:21.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:07:21.864+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:07:21.859+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:07:21.867+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:07:21.897+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.063 seconds
[2025-04-14T00:07:52.126+0000] {processor.py:186} INFO - Started process (PID=100) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:07:52.128+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:07:52.132+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:07:52.132+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:07:52.147+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:07:52.143+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:07:52.149+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:07:52.184+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.067 seconds
[2025-04-14T00:08:22.443+0000] {processor.py:186} INFO - Started process (PID=112) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:08:22.445+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:08:22.449+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:08:22.449+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:08:22.463+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:08:22.458+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:08:22.465+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:08:22.502+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.067 seconds
[2025-04-14T00:08:53.133+0000] {processor.py:186} INFO - Started process (PID=127) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:08:53.135+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:08:53.138+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:08:53.138+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:08:53.153+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:08:53.149+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:08:53.156+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:08:53.187+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.061 seconds
[2025-04-14T00:09:24.010+0000] {processor.py:186} INFO - Started process (PID=139) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:09:24.012+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:09:24.016+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:09:24.016+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:09:24.027+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:09:24.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:09:24.029+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:09:24.063+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.060 seconds
[2025-04-14T00:09:54.887+0000] {processor.py:186} INFO - Started process (PID=152) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:09:54.889+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:09:54.893+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:09:54.892+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:09:54.910+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:09:54.906+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:09:54.913+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:09:54.955+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.077 seconds
[2025-04-14T00:10:25.064+0000] {processor.py:186} INFO - Started process (PID=163) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:10:25.066+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:10:25.070+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:10:25.069+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:10:25.082+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:10:25.078+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:10:25.084+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:10:25.128+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.072 seconds
[2025-04-14T00:10:55.315+0000] {processor.py:186} INFO - Started process (PID=177) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:10:55.317+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:10:55.320+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:10:55.320+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:10:55.332+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:10:55.329+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:10:55.335+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:10:55.371+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.067 seconds
[2025-04-14T00:11:25.564+0000] {processor.py:186} INFO - Started process (PID=190) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:11:25.566+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:11:25.570+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:11:25.569+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:11:25.589+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:11:25.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:11:25.592+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:11:25.641+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.084 seconds
[2025-04-14T00:11:55.838+0000] {processor.py:186} INFO - Started process (PID=202) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:11:55.840+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:11:55.843+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:11:55.843+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:11:55.858+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:11:55.855+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:11:55.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:11:55.901+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.071 seconds
[2025-04-14T00:12:26.140+0000] {processor.py:186} INFO - Started process (PID=214) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:12:26.142+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:12:26.147+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:12:26.146+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:12:26.167+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:12:26.161+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:12:26.171+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:12:26.236+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.106 seconds
[2025-04-14T00:12:56.470+0000] {processor.py:186} INFO - Started process (PID=225) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:12:56.472+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:12:56.476+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:12:56.476+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:12:56.491+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:12:56.486+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:12:56.495+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:12:56.533+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.071 seconds
[2025-04-14T00:13:27.021+0000] {processor.py:186} INFO - Started process (PID=236) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:13:27.023+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:13:27.026+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:13:27.025+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:13:27.038+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:13:27.034+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:13:27.040+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:13:27.086+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.076 seconds
[2025-04-14T00:13:57.324+0000] {processor.py:186} INFO - Started process (PID=247) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:13:57.326+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:13:57.329+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:13:57.328+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:13:57.341+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:13:57.337+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:13:57.343+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:13:57.373+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.058 seconds
[2025-04-14T00:14:28.329+0000] {processor.py:186} INFO - Started process (PID=258) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:14:28.331+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:14:28.335+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:14:28.334+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:14:28.352+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:14:28.347+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:14:28.356+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:14:28.402+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.082 seconds
[2025-04-14T00:14:59.308+0000] {processor.py:186} INFO - Started process (PID=269) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:14:59.310+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:14:59.314+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:14:59.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:14:59.326+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:14:59.322+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:14:59.328+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:14:59.364+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.063 seconds
[2025-04-14T00:15:30.202+0000] {processor.py:186} INFO - Started process (PID=282) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:15:30.204+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:15:30.207+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:15:30.207+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:15:30.219+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:15:30.215+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:15:30.221+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:15:30.259+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.065 seconds
[2025-04-14T00:16:01.152+0000] {processor.py:186} INFO - Started process (PID=293) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:16:01.154+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:16:01.158+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:16:01.157+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:16:01.170+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:16:01.166+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:16:01.173+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:16:01.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.063 seconds
[2025-04-14T00:16:32.172+0000] {processor.py:186} INFO - Started process (PID=305) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:16:32.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:16:32.176+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:16:32.176+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:16:32.189+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:16:32.185+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:16:32.191+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:16:32.222+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.058 seconds
[2025-04-14T00:17:02.496+0000] {processor.py:186} INFO - Started process (PID=317) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:17:02.498+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:17:02.504+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:17:02.504+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:17:02.524+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:17:02.519+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:17:02.528+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:17:02.574+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.088 seconds
[2025-04-14T00:17:32.949+0000] {processor.py:186} INFO - Started process (PID=331) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:17:32.952+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:17:32.957+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:17:32.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:17:32.976+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:17:32.971+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:17:32.979+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:17:33.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.082 seconds
[2025-04-14T00:18:03.299+0000] {processor.py:186} INFO - Started process (PID=342) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:18:03.301+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:18:03.304+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:18:03.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:18:03.321+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:18:03.316+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:18:03.325+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:18:03.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.092 seconds
[2025-04-14T00:18:33.609+0000] {processor.py:186} INFO - Started process (PID=355) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:18:33.612+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:18:33.614+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:18:33.613+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:18:33.628+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:18:33.625+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:18:33.630+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:18:33.664+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.064 seconds
[2025-04-14T00:19:03.882+0000] {processor.py:186} INFO - Started process (PID=370) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:19:03.885+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:19:03.887+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:19:03.887+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:19:03.899+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:19:03.895+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:19:03.902+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:19:03.944+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.071 seconds
[2025-04-14T00:19:34.159+0000] {processor.py:186} INFO - Started process (PID=381) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:19:34.161+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:19:34.164+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:19:34.163+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:19:34.179+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:19:34.175+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:19:34.181+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:19:34.217+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.065 seconds
[2025-04-14T00:20:04.428+0000] {processor.py:186} INFO - Started process (PID=393) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:20:04.431+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:20:04.434+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:20:04.433+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:20:04.449+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:20:04.445+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:20:04.452+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:20:04.488+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.071 seconds
[2025-04-14T00:20:34.561+0000] {processor.py:186} INFO - Started process (PID=405) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:20:34.563+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:20:34.566+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:20:34.565+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:20:34.582+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:20:34.578+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:20:34.585+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:20:34.623+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.069 seconds
[2025-04-14T00:21:04.767+0000] {processor.py:186} INFO - Started process (PID=418) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:21:04.769+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:21:04.770+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:21:04.770+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:21:04.783+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:21:04.779+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:21:04.785+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:21:04.815+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.055 seconds
[2025-04-14T00:21:35.717+0000] {processor.py:186} INFO - Started process (PID=430) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:21:35.719+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:21:35.722+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:21:35.721+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:21:35.739+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:21:35.735+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:21:35.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:21:35.783+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.075 seconds
[2025-04-14T00:22:06.009+0000] {processor.py:186} INFO - Started process (PID=441) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:22:06.010+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:22:06.011+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:22:06.011+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:22:06.023+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:22:06.019+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:22:06.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:22:06.054+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.054 seconds
[2025-04-14T00:22:36.301+0000] {processor.py:186} INFO - Started process (PID=452) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:22:36.302+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:22:36.305+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:22:36.304+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:22:36.318+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:22:36.314+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:22:36.320+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:22:36.365+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.073 seconds
[2025-04-14T00:23:06.520+0000] {processor.py:186} INFO - Started process (PID=465) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:23:06.523+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:23:06.525+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:23:06.525+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:23:06.542+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:23:06.537+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:23:06.544+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:23:06.590+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.079 seconds
[2025-04-14T00:23:37.492+0000] {processor.py:186} INFO - Started process (PID=476) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:23:37.494+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:23:37.497+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:23:37.496+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:23:37.512+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:23:37.508+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:23:37.516+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:23:37.553+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.072 seconds
[2025-04-14T00:24:08.461+0000] {processor.py:186} INFO - Started process (PID=488) to work on /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:24:08.463+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/dag_teste2.py for tasks to queue
[2025-04-14T00:24:08.466+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:24:08.465+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:24:08.483+0000] {logging_mixin.py:190} INFO - [2025-04-14T00:24:08.478+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/dag_teste2.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/dag_teste2.py", line 21, in <module>
    python_callable=hello,
                    ^^^^^
NameError: name 'hello' is not defined. Did you mean: 'help'?
[2025-04-14T00:24:08.500+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/dag_teste2.py
[2025-04-14T00:24:08.549+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/dag_teste2.py took 0.101 seconds
